environment:
  # Project path
  projectPath: /Users/liudonghua/code/flutter/code_push_demo
  # Flutter SDK
  flutterSdkPath: /Users/liudonghua/apps/flutter
  # Compile cache path
  buildCachePath: /tmp/dart_compile_cache
  # FTP
  ftpConfig: 192.168.80.141|root|123456
